version: '3'
services:
  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "foobared"]
    ports:
      - "6379:6379"

  worker:
    build: .
    volumes:
      - .:/app
    command: python manage.py rqworker default
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=foobared
